<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>ReceiptVault.Server</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Data.Tables" Version="12.9.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Shared\ReceiptVault.Shared.csproj" />
	</ItemGroup>

</Project>
